version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - dudoser-net
    environment:
      FRONTEND_URI: '_'
    volumes:
      - ./deployments/default.conf:/etc/nginx/conf.d/default.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

  frontend:
    image: ghcr.io/dudoserovich/egt_frontend:latest
    networks:
      - dudoser-net
    command: npm start

  backend:
    image: ghcr.io/dudoserovich/egt_backend:latest
    restart: on-failure
    environment:
      WEB_DOCUMENT_ROOT: '/app/public'
      DATABASE_URL: "mysql://user:password@db:3306/edu_game_theory?serverVersion=5.7.27&charset=utf8"
    networks:
      - dudoser-net

  # TODO: В будущем нужна защита чувствительных данных
  db:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - dudoser-net
    environment:
      MYSQL_DATABASE: "edu_game_theory"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

volumes:
  mysql-data: {}

networks:
  dudoser-net: {}

