version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      FRONTEND_URI: '_'
    volumes:
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf:delegated
    command: [nginx-debug, '-g', 'daemon off;']

  frontend:
    image: the_dudoser/egt_frontend
    volumes:
      - ./client:/app:delegated
    command: npm start

  backend:
    image: the_dudoser/egt_backend
    restart: on-failure
    build:
      args:
        ENV: dev
    volumes:
      - ./server:/app:delegated
    environment:
      WEB_DOCUMENT_ROOT: '/app/public'
      DATABASE_URL: "mysql://user:password@db:3306/edu_game_theory?serverVersion=5.7.27&charset=utf8"

  db:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "edu_game_theory"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

volumes:
  mysql-data: {}

