version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - backend-notifier
    networks:
      - dudoser-net
    environment:
      FRONTEND_URI: '_'
    volumes:
      - ./deployments/default.conf:/etc/nginx/conf.d/default.conf:ro
    command: [nginx-debug, '-g', 'daemon off;'] # Подробное логирование

  frontend:
    image: ghcr.io/dudoserovich/egt_frontend:latest
    networks:
      - dudoser-net
    command: npm start

  backend:
    image: ghcr.io/dudoserovich/egt_backend:latest
    restart: on-failure
    build:
      args:
        ENV: prod
    environment:
      WEB_DOCUMENT_ROOT: '/app/public'
      DATABASE_URL: "mysql://user:password@db:3306/edu_game_theory?serverVersion=5.7.27&charset=utf8"
    networks:
      - dudoser-net

  db:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - dudoser-net
    environment:
      MYSQL_DATABASE: "edu_game_theory"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

  ###> symfony/mercure-bundle ###
  backend-notifier:
    image: dunglas/mercure
    restart: unless-stopped
    networks:
      - dudoser-net
    depends_on:
      - backend
    environment:
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.HYO3bkOHodu0Xxdt7SOwCWKixD-gyKfbhtXZDc2OA2Q
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      PUBLISH_ALLOWED_ORIGINS: '*'
      MERCURE_CORS_ALLOWED_ORIGINS: '*'
      ALLOW_ANONYMOUS: 1
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins *
    # Comment the following line to disable the development mode
    #command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      #      - ./server:/app:delegated
      - mercure_data:/data
      - mercure_config:/config
  ###< symfony/mercure-bundle ###

volumes:
  mysql-data: {}
  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
  ###< symfony/mercure-bundle ###

networks:
  dudoser-net: {}

