version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      FRONTEND_URI: '_'
    volumes:
      - ./deployments/default.conf:/etc/nginx/conf.d/default.conf:delegated
    command: [nginx-debug, '-g', 'daemon off;']

  frontend:
    ports:
      - "8090:8090"
    image: the_dudoser/egt_frontend
    volumes:
      - ./client:/app:delegated
    command: npm start

  backend:
    ports:
      - "8080:8080"
    image: the_dudoser/egt_backend
    restart: on-failure
    volumes:
      - ./server:/app:delegated
    environment:
      WEB_DOCUMENT_ROOT: '/app/public'
      DATABASE_URL: "mysql://user:password@db:3306/edu_game_theory?serverVersion=5.7.27&charset=utf8"
      APP_DEBUG: "true"
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "start_with_request=yes client_port=9007 client_host=172.18.0.1"
      XDEBUG_SESSION: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=backend"

  db:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "edu_game_theory"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

volumes:
  mysql-data: {}

