version: "3.7"

services:
  balancer:
    image: nginx:1.19.7-alpine
    depends_on:
      - web
      - frontend
    ports:
      - "80:8080"
    restart: always
    volumes:
      - ./deployments/docker/balancer/nginx.conf:/etc/nginx/nginx.conf:delegated

  frontend:
    build:
      context: client
      dockerfile: docker/nginx/Dockerfile
      target: node-builder
    working_dir: /app
    volumes:
      - ./client:/app:delegated
    command: npm start

  restarter:
    image: docker
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 600; docker restart edugametheory-frontend-1; done" ]
    restart: unless-stopped

  php-fpm:
    image: edu-game-theory/server-php-fpm
    pull_policy: build
    build:
      context: server
      dockerfile: docker/php/Dockerfile
      args:
        ENV: dev
        XDEBUG_ENABLED: 0
    working_dir: /app
    restart: on-failure
    volumes:
      - ./server:/app:delegated
    depends_on:
      - 'mysql'
    environment:
      APP_DEBUG: "true"
      DATABASE_URL: "mysql://user:password@mysql:3306/edu_game_theory?serverVersion=5.7.27&charset=utf8"
#      XDEBUG_MODE: "debug"
      #XDEBUG_CONFIG: "start_with_request=yes client_port=9007 client_host=host.docker.internal"
#      XDEBUG_CONFIG: "start_with_request=yes client_port=9007 client_host=172.18.0.1"
#      XDEBUG_SESSION: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=edu_game_theory"
      ROUTER_HOST: "localhost"
      ROUTER_SCHEME: 'http'
      ROUTER_BASE_URL: ''

  web:
    build:
      context: server
      dockerfile: docker/nginx/Dockerfile
      args:
        PHP_IMAGE: edu-game-theory/server-php-fpm
    working_dir: /app
    restart: on-failure
    volumes:
      - ./server:/app:delegated
    depends_on:
      - 'php-fpm'
    ports:
#      - "80:8080"
      - "8080:8080"
    environment:
      NGINX_HOST: "localhost"
      NGINX_HTTP_PORT: "80"
      NGINX_HTTPS: "off"

  mysql:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - '3306'
    ports:
      - '8092:3306'
    environment:
      MYSQL_DATABASE: "edu_game_theory"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql-data:/var/lib/mysql:delegated

volumes:
  mysql-data: {}
