# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"
    twig:
        mode: lazy
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public/uploads"
                cache_prefix: "media/cache"
    filter_sets:
        cache: ~
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [120, 90]
                    mode: outbound