nelmio_api_doc:
    models:
        names:
            - { alias: User,                  type: App\Entity\User,                  groups: [ "default" ] }
            - { alias: Term,                  type: App\Entity\Term,                  groups: [ "default" ] }
            - { alias: Task,                  type: App\Entity\Task,                  groups: [ "default" ] }
            - { alias: Achievement,           type: App\Entity\Achievement,           groups: [ "default" ] }
            - { alias: Topic,                 type: App\Entity\Topic,                 groups: [ "default" ] }
            - { alias: TaskMark,              type: App\Entity\TaskMark,              groups: [ "default" ] }
            - { alias: Education,             type: App\Entity\Education,             groups: [ "default" ] }
            - { alias: EducationTasks,        type: App\Entity\EducationTasks,        groups: [ "default" ] }
            - { alias: UserAchievement,       type: App\Entity\UserAchievement,       groups: [ "default" ] }
            - { alias: UserEducation,         type: App\Entity\UserEducation,         groups: [ "default" ] }

            - alias: UserView1
              type: App\Schema\UserView
              groups: [ "id", "fio" ]
            - alias: UserView
              type: App\Schema\UserView
              groups: [ "default" ]
            - alias: TermView
              type: App\Schema\TermView
              groups: [ "default" ]
            - alias: TaskView
              type: App\Schema\TaskView
              groups: [ "default" ]
            - alias: AchievementView
              type: App\Schema\AchievementView
              groups: [ "default" ]
            - alias: TopicView
              type: App\Schema\TopicView
              groups: [ "default" ]
            - alias: TaskMarkView
              type: App\Schema\TaskMarkView
              groups: [ "default" ]
            - alias: EducationView
              type: App\Schema\EducationView
              groups: [ "default" ]
            - alias: EducationTasksView
              type: App\Schema\EducationTasksView
              groups: [ "default" ]
            - alias: UserAchievementView
              type: App\Schema\UserAchievementView
              groups: [ "default" ]
            - alias: UserEducationView
              type: App\Schema\UserEducationView
              groups: [ "default" ]
    documentation:
        info:
            title: EduGameTheory
            description: Здесь описан контракт между фронтом и бэком
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: |
                        #### Может быть получен при помощи команды:
                        ## `php bin/console lexik:jwt:generate-token -c App\\Entity\\User -t <seconds> <login>`
                        #### Пример команды:
                        ## `php bin/console lexik:jwt:generate-token -c App\\Entity\\User -t 86400 admin`
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        disable_default_routes: true
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
