apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - image: harbor.drom.ru/drom-upgrade/frontend:latest
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 8090
              name: nginx
          workingDir: /app
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sleep", "10" ]
          readinessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
              ephemeral-storage: "10Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
              ephemeral-storage: "100Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - name: http
      port: 8090
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
  clusterIP: None
