apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/component: server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/component: server
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: server-config
          image: harbor.drom.ru/drom-upgrade/server-php-fpm:latest
          imagePullPolicy: Always
          name: php-fpm
          ports:
            - containerPort: 9000
              name: php-fpm
          workingDir: /app
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sleep", "10" ]
          volumeMounts:
            - name: jwt-credentials
              mountPath: /app/config/jwt
          readinessProbe:
            exec:
              command:
                - php-fpm-healthcheck
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
              ephemeral-storage: "10Mi"
            limits:
              cpu: "200m"
              memory: "150Mi"
              ephemeral-storage: "100Mi"
        - envFrom:
            - configMapRef:
                name: server-config
          image: harbor.drom.ru/drom-upgrade/server-nginx:latest
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 8080
              name: nginx
          workingDir: /app
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sleep", "10" ]
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
              ephemeral-storage: "10Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
              ephemeral-storage: "100Mi"
      restartPolicy: Always
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - php-fpm
      volumes:
        - name: jwt-credentials
          secret:
            secretName: jwt-credentials
            items:
              - key: JWT_SECRET_KEY
                path: private.pem
              - key: JWT_PUBLIC_KEY
                path: public.pem
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/component: server
  clusterIP: None
