name: Publish server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

env:
  NAMESPACE: edu-game-theory
  PHP_IMAGE: edu-game-theory/server-php-fpm
  NGINX_IMAGE: edu-game-theory/server-nginx

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login
      env:
        DOCKER_USER: dudoserovich
        DOCKER_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build server images
      working-directory: ./server
      env:
        ENV: dev
      run: |
        echo "Building php-fpm"
        docker build --build-arg ENV=$ENV --file docker/php/Dockerfile --target=statless --tag ${{ env.PHP_IMAGE }}:latest .
        echo "Building nginx"
        docker build --build-arg PHP_IMAGE=${{ env.PHP_IMAGE }} --file docker/nginx/Dockerfile --tag ${{ env.NGINX_IMAGE }}:latest .
        
    - name: Docker push
      run: |
        docker push ${{ env.PHP_IMAGE }}:latest
        docker push ${{ env.NGINX_IMAGE }}:latest
