name: Publish server

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'backup/**'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'backup/**'
      - 'docs/**'

  workflow_dispatch:

env:
  PREFIX: ghcr.io/dudoserovich

jobs:

  check:
    name: Check changed files
    outputs:
      backend_service: ${{ steps.check_files.outputs.backend_service }}
      frontend_service: ${{ steps.check_files.outputs.frontend_service }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file; do
            echo $file
            if [[ $file == client/* ]]; then
              echo "::set-output name=frontend_service::true"
            elif [[ $file == server/* ]]; then
              echo "::set-output name=backend_service::true"
            else
              echo "file does not belong to any service"
            fi
          done < files.txt

  backend_service:
    needs: [check]
    if: needs.check.outputs.backend_service == 'true'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: egt_backend
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: sudo docker build ./server -t $IMAGE_NAME

      - name: Login to GitHub container Registry
        run: echo "${{ secrets.PACKAGES_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Post image to github packages
        run: |
          IMAGE_ID=$PREFIX/$IMAGE_NAME
          VERSION=${GITHUB_SHA::7}
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  frontend_service:
    needs: [check]
    if: needs.check.outputs.frontend_service == 'true'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: egt_frontend
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: sudo docker build ./client -t $IMAGE_NAME

      - name: Login to GitHub container Registry
        run: echo "${{ secrets.PACKAGES_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Post image to github packages
        run: |
          IMAGE_ID=$PREFIX/$IMAGE_NAME
          VERSION=${GITHUB_SHA::7}
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          
  # Отправка сообщений telegram-ботом, если один из образов билдился
  # P.S. Пока отправка сообщений настроена только на владельца репозитория :D
  send_telegram:
      needs: [backend_service, frontend_service]
      # Условие до outputs говорит о том, что job нужно запускать независимо от того, 
      #   что предыдущие job могут быть пропущены
      # Оставшаяся часть условия говорит о том, что не нужно ничего отправлять если оба образа не билдились
      if: ${{ 
        !cancelled() 
        && (success() || failure()) 
        && (needs.check.outputs.frontend_service == 'true' || needs.check.outputs.backend_service == 'true')
        }}
      runs-on: ubuntu-latest
      steps:
      
      - name: Send message with status backend_service and frontend_service
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: 'html'
          message: |
            <strong>Репозиторий:</strong> ${{ github.repository }}
            <strong>Активизатор:</strong> ${{ github.actor }}
            
            <i>Отработал процесс публикации со статусами сервисов:</i>
            - <pre>backend_service</pre>: ${{ needs.backend_service.result }}
            - <pre>frontend_service</pre>: ${{ needs.frontend_service.result }}
            
            <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">Action</a>
            <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">Посмотреть изменения</a>
