name: telegram message
on: [workflow_dispatch]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          photo: 'https://cataas.com/cat'
          sticker: "https://github.com/TelegramBots/book/raw/master/src/docs/sticker-fred.webp"
